--Proverbios del 13 al 15
--Grupo 053 
--Sebastian Alejandro Rubio Valencia #2127340
--Jose Emiliano Frias Felix #1962531
INSERT INTO Versiculos (Id_Version, Id_Libro, NumeroCap, NumeroVers, Texto)
VALUES  (1,20,13,1,'El hijo sabio recibe el consejo del padre; Mas el burlador no escucha las reprensiones.'),
		(1,20,13,2,'Del fruto de su boca el hombre comerá el bien; Mas el alma de los prevaricadores hallará el mal.'),
		(1,20,13,3,'El que guarda su boca guarda su alma; Mas el que mucho abre sus labios tendrá calamidad.'),
		(1,20,13,4,'El alma del perezoso desea, y nada alcanza; Mas el alma de los diligentes será prosperada.'),
		(1,20,13,5,'El justo aborrece la palabra de mentira; Mas el impío se hace odioso e infame.'),
		(1,20,13,6,'La justicia guarda al de perfecto camino; Mas la impiedad trastornará al pecador.'),
		(1,20,13,7,'Hay quienes pretenden ser ricos, y no tienen nada; Y hay quienes pretenden ser pobres, y tienen muchas riquezas.'),
		(1,20,13,8,'El rescate de la vida del hombre está en sus riquezas; Pero el pobre no oye censuras.'),
		(1,20,13,9,'La luz de los justos se alegrará; Mas se apagará la lámpara de los impíos.'),
		(1,20,13,10,'Ciertamente la soberbia concebirá contienda; Mas con los avisados está la sabiduría.'),
		(1,20,13,11,'Las riquezas de vanidad disminuirán; Pero el que recoge con mano laboriosa las aumenta.'),
		(1,20,13,12,'La esperanza que se demora es tormento del corazón; Pero árbol de vida es el deseo cumplido.') ,
		(1,20,13,13,'El que menosprecia el precepto perecerá por ello; Mas el que teme el mandamiento será recompensado.'),
		(1,20,13,14,'La ley del sabio es manantial de vida Para apartarse de los lazos de la muerte.'),
		(1,20,13,15,'El buen entendimiento da gracia; Mas el camino de los transgresores es duro.'),
		(1,20,13,16,'Todo hombre prudente procede con sabiduría; Mas el necio manifestará necedad.'),
		(1,20,13,17,'El mal mensajero acarrea desgracia; Mas el mensajero fiel acarrea salud.'),
		(1,20,13,18,'Pobreza y vergüenza tendrá el que menosprecia el consejo; Mas el que guarda la corrección recibirá honra.'),
		(1,20,13,19,'El deseo cumplido regocija el alma; Pero apartarse del mal es abominación a los necios.'),
		(1,20,13,20,'El que anda con sabios, sabio será; Mas el que se junta con necios será quebrantado.'),
		(1,20,13,21,'El mal perseguirá a los pecadores, Mas los justos serán premiados con el bien.'),
		(1,20,13,22,'El bueno dejará herederos a los hijos de sus hijos; Pero la riqueza del pecador está guardada para el justo.'),
		(1,20,13,23,'En el barbecho de los pobres hay mucho pan; Mas se pierde por falta de juicio.'),
		(1,20,13,24,'El que detiene el castigo, a su hijo aborrece; Mas el que lo ama, desde temprano lo corrige.'),
		(1,20,13,25,'El justo come hasta saciar su alma; Mas el vientre de los impíos tendrá necesidad.'),
		(1,20,14,1,'La mujer sabia edifica su casa; Mas la necia con sus manos la derriba.'),
		(1,20,14,2,'El que camina en su rectitud teme a Jehová; Mas el de caminos pervertidos lo menosprecia.'),
		(1,20,14,3,'En la boca del necio está la vara de la soberbia; Mas los labios de los sabios los guardarán.'),
		(1,20,14,4,'Sin bueyes el granero está vacío; Mas por la fuerza del buey hay abundancia de pan.'),
		(1,20,14,5,'El testigo verdadero no mentirá; Mas el testigo falso hablará mentiras.'),
		(1,20,14,6,'Busca el escarnecedor la sabiduría y no la halla; Mas al hombre entendido la sabiduría le es fácil.'),
		(1,20,14,7,'Vete de delante del hombre necio, Porque en él no hallarás labios de ciencia.'),
		(1,20,14,8,'a ciencia del prudente está en entender su camino; Mas la indiscreción de los necios es engaño.'),
		(1,20,14,9,'Los necios se mofan del pecado; Mas entre los rectos hay buena voluntad.'),
		(1,20,14,10,'El corazón conoce la amargura de su alma; Y extraño no se entremeterá en su alegría.'),
		(1,20,14,11,'La casa de los impíos será asolada; Pero florecerá la tienda de los rectos.'),
		(1,20,14,12,'Hay camino que al hombre le parece derecho; Pero su fin es camino de muerte.'),
		(1,20,14,13,'Aun en la risa tendrá dolor el corazón; Y el término de la alegría es congoja.'),
		(1,20,14,14,'De sus caminos será hastiado el necio de corazón; Pero el hombre de bien estará contento del suyo.'),
		(1,20,14,15,'El simple todo lo cree; Mas el avisado mira bien sus pasos.'),
		(1,20,14,16,'El sabio teme y se aparta del mal; Mas el insensato se muestra insolente y confiado.'),
		(1,20,14,17,'El que fácilmente se enoja hará locuras; Y el hombre perverso será aborrecido.'),
		(1,20,14,18,'Los simples heredarán necedad; Mas los prudentes se coronarán de sabiduría.'),
		(1,20,14,19,'Los malos se inclinarán delante de los buenos, Y los impíos a las puertas del justo.'),
		(1,20,14,20,'El pobre es odioso aun a su amigo; Pero muchos son los que aman al rico.'),
		(1,20,14,21,'Peca el que menosprecia a su prójimo; Mas el que tiene misericordia de los pobres es bienaventurado.'),
		(1,20,14,22,'¿No yerran los que piensan el mal? Misericordia y verdad alcanzarán los que piensan el bien.'),
		(1,20,14,23,'En toda labor hay fruto; Mas las vanas palabras de los labios empobrecen.'),
		(1,20,14,24,'Las riquezas de los sabios son su corona; Pero la insensatez de los necios es infatuación.'),
		(1,20,14,25,'El testigo verdadero libra las almas; Mas el engañoso hablará mentiras.'),
		(1,20,14,26,'En el temor de Jehová está la fuerte confianza; Y esperanza tendrán sus hijos.'),
		(1,20,14,27,'El temor de Jehová es manantial de vida Para apartarse de los lazos de la muerte.'),
		(1,20,14,28,'En la multitud del pueblo está la gloria del rey; Y en la falta de pueblo la debilidad del príncipe.'),
		(1,20,14,29,'El que tarda en airarse es grande de entendimiento; Mas el que es impaciente de espíritu enaltece la necedad.'),
		(1,20,14,30,'El corazón apacible es vida de la carne; Mas la envidia es carcoma de los huesos.'),
		(1,20,14,31,'El que oprime al pobre afrenta a su Hacedor; Mas el que tiene misericordia del pobre, lo honra.'),
		(1,20,14,32,'Por su maldad será lanzado el impío; Mas el justo en su muerte tiene esperanza.'),
		(1,20,14,33,'En el corazón del prudente reposa la sabiduría; Pero no es conocida en medio de los necios.'),
		(1,20,14,34,'La justicia engrandece a la nación; Mas el pecado es afrenta de las naciones.'),
		(1,20,14,35,'La benevolencia del rey es para con el servidor entendido; Mas su enojo contra el que lo avergüenza.'),
		(1,20,15,1,'La blanda respuesta quita la ira; Mas la palabra áspera hace subir el furor.'),
		(1,20,15,2,'La lengua de los sabios adornará la sabiduría; Mas la boca de los necios hablará sandeces.'),
		(1,20,15,3,'Los ojos de Jehová están en todo lugar, Mirando a los malos y a los buenos.'),
		(1,20,15,4,'La lengua apacible es árbol de vida; Mas la perversidad de ella es quebrantamiento de espíritu.'),
		(1,20,15,5,'El necio menosprecia el consejo de su padre; Mas el que guarda la corrección vendrá a ser prudente.'),
		(1,20,15,6,'En la casa del justo hay gran provisión; Pero turbación en las ganancias del impío.'),
		(1,20,15,7,'La boca de los sabios esparce sabiduría; No así el corazón de los necios.'),
		(1,20,15,8,'El sacrificio de los impíos es abominación a Jehová; Mas la oración de los rectos es su gozo.'),
		(1,20,15,9,'Abominación es a Jehová el camino del impío; Mas él ama al que sigue justicia.'),
		(1,20,15,10,'La reconvención es molesta al que deja el camino; Y el que aborrece la corrección morirá.'),
		(1,20,15,11,'El Seol y el Abadón están delante de Jehová; ¡Cuánto más los corazones de los hombres!'),
		(1,20,15,12,'El escarnecedor no ama al que le reprende, Ni se junta con los sabios.'),
		(1,20,15,13,'El corazón alegre hermosea el rostro; Mas por el dolor del corazón el espíritu se abate.'),
		(1,20,15,14,'El corazón entendido busca la sabiduría; Mas la boca de los necios se alimenta de necedades.'),
		(1,20,15,15,'Todos los días del afligido son difíciles; Mas el de corazón contento tiene un banquete continuo.'),
		(1,20,15,16,'Mejor es lo poco con el temor de Jehová, Que el gran tesoro donde hay turbación.'),
		(1,20,15,17,'Mejor es la comida de legumbres donde hay amor, Que de buey engordado donde hay odio.'),
		(1,20,15,18,'El hombre iracundo promueve contiendas; Mas el que tarda en airarse apacigua la rencilla.'),
		(1,20,15,19,'El camino del perezoso es como seto de espinos; Mas la vereda de los rectos, como una calzada.'),
		(1,20,15,20,'El hijo sabio alegra al padre; Mas el hombre necio menosprecia a su madre.'),
		(1,20,15,21,'La necedad es alegría al falto de entendimiento; Mas el hombre entendido endereza sus pasos.'),
		(1,20,15,22,'Los pensamientos son frustrados donde no hay consejo; Mas en la multitud de consejeros se afirman.'),
		(1,20,15,23,'El hombre se alegra con la respuesta de su boca; Y la palabra a su tiempo, ¡cuán buena es!'),
		(1,20,15,24,'El camino de la vida es hacia arriba al entendido, Para apartarse del Seol abajo.'),
		(1,20,15,25,'Jehová asolará la casa de los soberbios; Pero afirmará la heredad de la viuda.'),
		(1,20,15,26,'Abominación son a Jehová los pensamientos del malo; Mas las expresiones de los limpios son limpias.'),
		(1,20,15,27,'Alborota su casa el codicioso; Mas el que aborrece el soborno vivirá.'),
		(1,20,15,28,'El corazón del justo piensa para responder; Mas la boca de los impíos derrama malas cosas.'),
		(1,20,15,29,'Jehová está lejos de los impíos; Pero él oye la oración de los justos.'),
		(1,20,15,30,'La luz de los ojos alegra el corazón, Y la buena nueva conforta los huesos.'),
		(1,20,15,31,'El oído que escucha las amonestaciones de la vida, Entre los sabios morará.'),
		(1,20,15,32,'El que tiene en poco la disciplina menosprecia su alma; Mas el que escucha la corrección tiene entendimiento.'),
		(1,20,15,33,'El temor de Jehová es enseñanza de sabiduría; Y a la honra precede la humildad. ');
