CREATE DATABASE MAD;
USE MAD;

CREATE TABLE Usuario 
(	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	ApPat VARCHAR(50) NOT NULL,
	ApMat VARCHAR(50) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	Genero BIT NOT NULL,
	Correo VARCHAR(50) NOT NULL UNIQUE,
	ID_Contraseñas INT NOT NULL UNIQUE,
	ID_IdiomaPreferido INT NOT NULL,
	CodigoRec SMALLINT NOT NULL,
	Estatus BIT NOT NULL,
	TamañoLetra INT NOT NULL,
	Fecha_HoraRegistro SMALLDATETIME NOT NULL,
	FechaBaja DATE
	);

CREATE TABLE Favorito
(	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL UNIQUE,
	"Version" SMALLINT NOT NULL,
	Libro SMALLINT NOT NULL,
	Capitulo TINYINT NOT NULL,
	Versiculo TINYINT,
	ID_Usuario INT NOT NULL,
	Hora_Fecha SMALLDATETIME,
	);

CREATE TABLE Historial
(	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Palabras VARCHAR(100) NOT NULL,
	"Version" SMALLINT NOT NULL,
	Testamento SMALLINT,
	Libro SMALLINT,
	ID_Usuario INT NOT NULL,
	Hora_Fecha SMALLDATETIME
	);
		DROP TABLE Contraseñas

CREATE TABLE Contraseñas
(	ID INT PRIMARY KEY IDENTITY(1,1),
	ContraseñaActual VARCHAR(50),
	ContraseñaAnterior1 VARCHAR(50),
	ContraseñaAnterior2 VARCHAR(50)
	);
		DROP TABLE Idiomas

CREATE TABLE Idiomas
(	ID INT PRIMARY KEY IDENTITY(1,1),
	Idioma VARCHAR(50)
	);

ALTER TABLE Usuario
	ADD CONSTRAINT FK_ID_Contraseñas
		FOREIGN KEY (ID_Contraseñas)
			REFERENCES Contraseñas (ID)
			ON DELETE CASCADE;

ALTER TABLE Usuario
	ADD CONSTRAINT FK_ID_IdiomaPreferido
		FOREIGN KEY (ID_IdiomaPreferido)
			REFERENCES Idiomas (ID)
			ON DELETE CASCADE;

ALTER TABLE Favorito
	ADD CONSTRAINT FK_Favorito_ID_Usuario
		FOREIGN KEY (ID_Usuario)
			REFERENCES Usuario (ID)
			ON DELETE CASCADE;

ALTER TABLE Historial
	ADD CONSTRAINT FK_Historial_ID_Usuario
		FOREIGN KEY (ID_Usuario)
			REFERENCES Usuario (ID)
			ON DELETE CASCADE;
INSERT INTO IDIOMAS (Idioma) VALUES ('Español'), ('Ingles');

			--JOSE EMILIANO FRIAS FELIX
			--SEBASTIAN ALEJANDRO RUBIO VALENCIA 

			SELECT * FROM Contraseñas